# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  volta_chan_config = debug

else ifeq ($(config),release)
  volta_chan_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := volta-chan

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

volta-chan:
ifneq (,$(volta_chan_config))
	@echo "==== Building volta-chan ($(volta_chan_config)) ===="
	@${MAKE} --no-print-directory -C . -f volta-chan.make config=$(volta_chan_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f volta-chan.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   volta-chan"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"